# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas', models.CharField(max_length=40, verbose_name='\u533a')),
                ('zipcode', models.IntegerField(verbose_name='\u90ae\u7f16')),
            ],
            options={
                'verbose_name': '\u533a',
                'verbose_name_plural': '\u533a',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cities', models.CharField(max_length=30, verbose_name='\u5e02')),
            ],
            options={
                'verbose_name': '\u5e02',
                'verbose_name_plural': '\u5e02',
            },
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5206\u7c7b\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b\u5217\u8868',
                'verbose_name_plural': '\u5206\u7c7b\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=150, verbose_name='\u5bc6\u7801')),
                ('tel', models.CharField(default='', max_length=12, verbose_name='\u624b\u673a\u53f7')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('integral', models.IntegerField(verbose_name='\u603b\u79ef\u5206')),
                ('consumption', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u6d88\u8d39\u989d')),
                ('reg_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('login_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6700\u540e\u767b\u5f55\u65f6\u95f4')),
                ('last_ip', models.URLField(default='', verbose_name='\u6700\u540e\u767b\u5f55ip\u5730\u5740')),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Classify', verbose_name='\u5206\u7c7b')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237\u5217\u8868',
                'verbose_name_plural': '\u5ba2\u6237\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(default='', max_length=16, verbose_name='\u8ba2\u5355\u7f16\u53f7')),
                ('status', models.IntegerField(choices=[(0, '\u5f85\u4ed8\u6b3e'), (1, '\u5df2\u652f\u4ed8'), (2, '\u5df2\u53d1\u8d27'), (3, '\u5df2\u5b8c\u6210'), (4, '\u5df2\u5173\u95ed'), (5, '\u9000\u6b3e\u4e2d')], verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('express_num', models.CharField(default='', max_length=16, verbose_name='\u5feb\u9012\u5355\u53f7')),
                ('info', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5907\u6ce8')),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5b9e\u4ed8\u91d1\u989d')),
                ('integral_get', models.IntegerField(verbose_name='\u83b7\u5f97\u79ef\u5206\u6570')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u8ba2\u5355\u521b\u5efa\u65f6\u95f4')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='\u5ba2\u6237')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u5217\u8868',
                'verbose_name_plural': '\u8ba2\u5355\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='\u6570\u91cf')),
                ('evaluate_level', models.IntegerField(blank=True, choices=[(0, '\u5dee\u8bc4'), (1, '\u4e2d\u8bc4'), (2, '\u597d\u8bc4')], null=True, verbose_name='\u8bc4\u4ef7\u7b49\u7ea7')),
                ('evaluate', models.TextField(blank=True, null=True, verbose_name='\u8bc4\u4ef7\u8be6\u60c5')),
                ('evaluate_time', models.DateTimeField(blank=True, null=True, verbose_name='\u8bc4\u4ef7\u65f6\u95f4')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsList', verbose_name='\u5546\u54c1')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Order', verbose_name='\u6240\u5c5e\u8ba2\u5355')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u5546\u54c1\u5217\u8868',
                'verbose_name_plural': '\u8ba2\u5355\u5546\u54c1\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinces', models.CharField(max_length=20, verbose_name='\u7701')),
            ],
            options={
                'verbose_name': '\u7701',
                'verbose_name_plural': '\u7701',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='provinces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Province', verbose_name='\u7701'),
        ),
        migrations.AddField(
            model_name='area',
            name='cities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.City', verbose_name='\u5e02'),
        ),
    ]
