# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20170809_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': '\u6536\u8d27\u5730\u5740', 'verbose_name_plural': '\u6536\u8d27\u5730\u5740\u5217\u8868'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '\u8ba2\u5355\u53f7', 'verbose_name_plural': '\u8ba2\u5355\u5217\u8868'},
        ),
        migrations.AlterModelOptions(
            name='ordergoods',
            options={'verbose_name': '\u8ba2\u5355\u5546\u54c1', 'verbose_name_plural': '\u8ba2\u5355\u5546\u54c1\u5217\u8868'},
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u53d1\u8d27\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u4ed8\u6b3e\u65f6\u95f4'),
        ),
    ]
