# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20170809_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='tel',
            field=models.CharField(default='', max_length=12, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Address', verbose_name='\u6536\u8d27\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='order',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='\u8fd0\u8d39'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_mode',
            field=models.IntegerField(blank=True, choices=[(0, '\u652f\u4ed8\u5b9d\u652f\u4ed8'), (1, '\u5fae\u4fe1\u652f\u4ed8'), (2, '\u8d27\u5230\u4ed8\u6b3e')], null=True, verbose_name='\u652f\u4ed8\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='order',
            name='express_num',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='\u5feb\u9012\u5355\u53f7'),
        ),
    ]
