# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 11:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_classify_require_integral'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u9000\u6b3e\u91d1\u989d')),
                ('reason', models.TextField(verbose_name='\u9000\u8d27\u539f\u56e0')),
                ('status', models.IntegerField(choices=[(0, '\u5ba1\u6838\u4e2d'), (1, '\u9000\u8d27\u4e2d'), (2, '\u9000\u6b3e\u6210\u529f')], verbose_name='\u9000\u8d27\u8ba2\u5355\u72b6\u6001')),
                ('express_num', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='\u9000\u8d27\u5feb\u9012\u5355\u53f7')),
                ('apply_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('complete_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='\u5ba2\u6237')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Order', verbose_name='\u6240\u5c5e\u8ba2\u5355')),
                ('order_goods', models.ManyToManyField(to='customers.OrderGoods', verbose_name='\u9000\u8d27\u5546\u54c1')),
            ],
            options={
                'verbose_name': '\u9000\u8d27\u8ba2\u5355',
                'verbose_name_plural': '\u9000\u8d27\u8ba2\u5355\u5217\u8868',
            },
        ),
    ]
