# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_returngoods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returngoods',
            name='customers',
        ),
    ]
