# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_remove_returngoods_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returngoods',
            name='order_goods',
            field=models.ManyToManyField(blank=True, null=True, to='customers.OrderGoods', verbose_name='\u9000\u8d27\u5546\u54c1'),
        ),
    ]
