# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20170810_1516'),
        ('customers', '0011_auto_20170810_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='coupon',
            field=models.ManyToManyField(to='goods.Coupon', verbose_name='\u4f18\u60e0\u5238'),
        ),
    ]
