# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_customer_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='coupon',
            field=models.ManyToManyField(blank=True, to='goods.Coupon', verbose_name='\u5df2\u9886\u53d6\u4f18\u60e0\u5238'),
        ),
        migrations.AlterField(
            model_name='returngoods',
            name='order_goods',
            field=models.ManyToManyField(blank=True, to='customers.OrderGoods', verbose_name='\u9000\u8d27\u5546\u54c1'),
        ),
    ]
