# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-21 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_auto_20170818_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='classify',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.Classify', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='coupon',
            field=models.ManyToManyField(blank=True, default='', to='goods.Coupon', verbose_name='\u5df2\u9886\u53d6\u4f18\u60e0\u5238'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='integral',
            field=models.IntegerField(default=0, verbose_name='\u603b\u79ef\u5206'),
        ),
    ]
