# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-21 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_auto_20170821_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '\u5ba2\u6237', 'verbose_name_plural': '\u5ba2\u6237\u5217\u8868'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='\u90ae\u7bb1'),
        ),
    ]
