# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_auto_20170821_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_icon',
            field=models.ImageField(default='customer/icon/newDefault.png', upload_to='customer/icon/', verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(default='\u4e00\u6167\u4f1a\u5458', max_length=100, verbose_name='\u7528\u6237\u6635\u79f0'),
        ),
    ]
