# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_auto_20170824_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u4f59\u989d'),
        ),
    ]
