# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_customer_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='recipient',
            field=models.CharField(default='', max_length=12, verbose_name='\u6536\u4ef6\u4eba'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_icon',
            field=models.ImageField(blank=True, default='customer/icon/newDefault.png', null=True, upload_to='customer/icon/', verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
    ]
