# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_coupon_explain'),
        ('customers', '0019_auto_20170828_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='props',
            field=models.ManyToManyField(to='goods.PropList', verbose_name='\u5546\u54c1\u5c5e\u6027'),
        ),
    ]
