# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_ordergoods_props'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customers',
        ),
    ]
