# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_coupon_explain'),
        ('customers', '0023_remove_ordergoods_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='Image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.Images', verbose_name='\u56fe\u7247'),
        ),
    ]
