# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_ordergoods_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='Image',
            new_name='image',
        ),
    ]
