# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0018_express'),
        ('customers', '0027_ordergoods_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='express_com',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Express', verbose_name='\u5feb\u9012\u516c\u53f8'),
        ),
    ]
