# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-27 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0029_cartgoods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartgoods',
            name='image',
        ),
        migrations.DeleteModel(
            name='CartGoods',
        ),
    ]
