# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-27 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0031_cartgoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartgoods',
            name='anonymous',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='\u533f\u540d\u53f7'),
        ),
        migrations.AlterField(
            model_name='cartgoods',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='\u7528\u6237'),
        ),
    ]
