# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-30 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0032_auto_20170927_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='integral_get',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u83b7\u5f97\u79ef\u5206\u6570'),
        ),
    ]
