# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0033_auto_20170930_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartgoods',
            name='single',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u76f4\u63a5\u8d2d\u4e70'),
        ),
    ]
