# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-17 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0024_goodslist_material_quality'),
        ('customers', '0034_cartgoods_single'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='follow',
            field=models.ManyToManyField(blank=True, to='goods.GoodsList', verbose_name='\u5173\u6ce8\u5546\u54c1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False, verbose_name='\u9ed8\u8ba4\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='classify',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='customers.Classify', verbose_name='\u5206\u7c7b'),
        ),
    ]
