# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-31 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0036_auto_20171030_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxoauth',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ACCESS_TOKEN'),
        ),
        migrations.AlterField(
            model_name='wxoauth',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='REFRESH_TOKEN'),
        ),
    ]
