# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0036_auto_20171030_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_icon',
            field=models.ImageField(blank=True, default='/media/customer/icon/newDefault.png', null=True, upload_to='customer/icon/', verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='wxoauth',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ACCESS_TOKEN'),
        ),
        migrations.AlterField(
            model_name='wxoauth',
            name='openid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='OpenID'),
        ),
        migrations.AlterField(
            model_name='wxoauth',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='REFRESH_TOKEN'),
        ),
    ]
