# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-31 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0037_auto_20171031_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_icon',
            field=models.ImageField(blank=True, default='/media/customer/icon/newDefault.png', null=True, upload_to='customer/icon/', verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
    ]
