# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0037_auto_20171101_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prepay_id',
            field=models.CharField(max_length=40, null=True, verbose_name='\u9884\u652f\u4ed8ID'),
        ),
        migrations.AlterField(
            model_name='cartgoods',
            name='anonymous',
            field=models.CharField(max_length=40, null=True, verbose_name='\u533f\u540d\u53f7'),
        ),
        migrations.AlterField(
            model_name='cartgoods',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='coupon',
            field=models.ManyToManyField(default='', to='goods.Coupon', verbose_name='\u5df2\u9886\u53d6\u4f18\u60e0\u5238'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='follow',
            field=models.ManyToManyField(to='goods.GoodsList', verbose_name='\u5173\u6ce8\u5546\u54c1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=150, null=True, verbose_name='\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tel',
            field=models.CharField(max_length=12, null=True, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_icon',
            field=models.ImageField(default='/media/customer/icon/newDefault.png', null=True, upload_to='customer/icon/', verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Address', verbose_name='\u6536\u8d27\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(null=True, verbose_name='\u53d1\u8d27\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='order',
            name='express_com',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Express', verbose_name='\u5feb\u9012\u516c\u53f8'),
        ),
        migrations.AlterField(
            model_name='order',
            name='express_num',
            field=models.CharField(default='', max_length=16, null=True, verbose_name='\u5feb\u9012\u5355\u53f7'),
        ),
        migrations.AlterField(
            model_name='order',
            name='info',
            field=models.CharField(max_length=100, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='order',
            name='integral_get',
            field=models.IntegerField(null=True, verbose_name='\u83b7\u5f97\u79ef\u5206\u6570'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_mode',
            field=models.IntegerField(choices=[(0, '\u652f\u4ed8\u5b9d\u652f\u4ed8'), (1, '\u5fae\u4fe1\u652f\u4ed8'), (2, '\u8d27\u5230\u4ed8\u6b3e')], null=True, verbose_name='\u652f\u4ed8\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_time',
            field=models.DateTimeField(null=True, verbose_name='\u4ed8\u6b3e\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='evaluate',
            field=models.TextField(null=True, verbose_name='\u8bc4\u4ef7\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='evaluate_level',
            field=models.IntegerField(choices=[(0, '\u5dee\u8bc4'), (1, '\u4e2d\u8bc4'), (2, '\u597d\u8bc4')], null=True, verbose_name='\u8bc4\u4ef7\u7b49\u7ea7'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='evaluate_time',
            field=models.DateTimeField(null=True, verbose_name='\u8bc4\u4ef7\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='returngoods',
            name='complete_time',
            field=models.DateTimeField(null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='returngoods',
            name='express_num',
            field=models.CharField(default='', max_length=16, null=True, verbose_name='\u9000\u8d27\u5feb\u9012\u5355\u53f7'),
        ),
        migrations.AlterField(
            model_name='returngoods',
            name='order_goods',
            field=models.ManyToManyField(to='customers.OrderGoods', verbose_name='\u9000\u8d27\u5546\u54c1'),
        ),
        migrations.AlterField(
            model_name='wxoauth',
            name='access_token',
            field=models.CharField(max_length=100, null=True, verbose_name='ACCESS_TOKEN'),
        ),
        migrations.AlterField(
            model_name='wxoauth',
            name='openid',
            field=models.CharField(max_length=50, null=True, verbose_name='OpenID'),
        ),
        migrations.AlterField(
            model_name='wxoauth',
            name='refresh_token',
            field=models.CharField(max_length=100, null=True, verbose_name='REFRESH_TOKEN'),
        ),
    ]
