# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0040_auto_20180315_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='integral',
        ),
        migrations.AddField(
            model_name='customer',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u4f63\u91d1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invitation_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u9080\u8bf7\u7801'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invitation_img',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='customer/icon/', verbose_name='\u63a8\u5e7f\u9080\u8bf7\u56fe'),
        ),
        migrations.AddField(
            model_name='customer',
            name='promote',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u63a8\u5e7f\u989d'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='classify',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.Endorsement', verbose_name='\u4ee3\u8a00\u4eba\u7ea7\u522b'),
        ),
    ]
