# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0041_auto_20180315_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='invitation_img',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='customer/invitation/', verbose_name='\u63a8\u5e7f\u9080\u8bf7\u56fe'),
        ),
    ]
