# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-02 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0041_auto_20171102_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u8ba2\u5355\u5b8c\u6210\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='order',
            name='express_num',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='\u5feb\u9012\u5355\u53f7'),
        ),
    ]
