# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-07 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0042_auto_20171102_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(default='', max_length=16, null=True, verbose_name='\u8ba2\u5355\u7f16\u53f7')),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5b9e\u4ed8\u91d1\u989d')),
                ('status', models.IntegerField(choices=[(0, '\u672a\u4ed8\u6b3e'), (1, '\u5df2\u6210\u529f')], default=0, verbose_name='\u72b6\u6001')),
                ('transfer_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u8f6c\u8d26\u65f6\u95f4')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='\u6240\u5c5e\u5ba2\u6237')),
            ],
            options={
                'verbose_name': '\u63d0\u9192\u8ba2\u5355',
                'verbose_name_plural': '\u63d0\u9192\u8ba2\u5355\u5217\u8868',
            },
        ),
    ]
