# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0042_auto_20180315_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='integral_get',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=100, verbose_name='\u6298\u6263'),
        ),
    ]
