# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0043_auto_20180315_2202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classify',
        ),
    ]
