# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-07 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0043_transferorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='coupon',
            field=models.ManyToManyField(blank=True, default='', null=True, to='goods.Coupon', verbose_name='\u5df2\u9886\u53d6\u4f18\u60e0\u5238'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='follow',
            field=models.ManyToManyField(blank=True, null=True, to='goods.GoodsList', verbose_name='\u5173\u6ce8\u5546\u54c1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_ip',
            field=models.URLField(blank=True, default='', null=True, verbose_name='\u6700\u540e\u767b\u5f55ip\u5730\u5740'),
        ),
    ]
