# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-07 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0024_goodslist_material_quality'),
        ('customers', '0044_auto_20171107_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Coupon', verbose_name='\u4f18\u60e0\u5238'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_icon',
            field=models.ImageField(blank=True, default='/media/customer/icon/newDefault.png', max_length=150, null=True, upload_to='customer/icon/', verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
    ]
