# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-16 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0045_customer_invited_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='red_packet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u7ea2\u5305'),
        ),
    ]
