# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-17 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0049_customer_red_packet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='\u9080\u8bf7\u7801'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='invited_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='\u88ab\u9080\u8bf7\u7801'),
        ),
        migrations.AlterField(
            model_name='wxoauth',
            name='openid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OpenID'),
        ),
    ]
