# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-27 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0050_auto_20180326_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankbin',
            options={'verbose_name': '\u94f6\u884cBIN', 'verbose_name_plural': '\u94f6\u884cBIN\u5217\u8868'},
        ),
    ]
