# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-18 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0051_auto_20180317_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=12, null=True, verbose_name='\u9080\u8bf7\u7801')),
            ],
            options={
                'verbose_name': '\u9080\u8bf7\u7801',
                'verbose_name_plural': '\u9080\u8bf7\u7801\u5217\u8868',
            },
        ),
        migrations.RemoveField(
            model_name='customer',
            name='invitation_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='invitation_img',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='invited_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='number_of_invited',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='promote_order',
        ),
        migrations.AddField(
            model_name='customer',
            name='invitation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_code', to='customers.Invitation', verbose_name='\u9080\u8bf7\u7801'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_code', to='customers.Invitation', verbose_name='\u88ab\u9080\u8bf7\u7801'),
        ),
        migrations.AddField(
            model_name='order',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Invitation', verbose_name='\u9080\u8bf7\u7801'),
        ),
    ]
