# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-07 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0053_auto_20180404_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_package',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u9886\u53d6\u7ea2\u5305'),
        ),
    ]
