# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-23 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0054_order_reduced'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferorders',
            name='remark',
            field=models.CharField(max_length=80, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '\u5f85\u4ed8\u6b3e'), (1, '\u5df2\u652f\u4ed8'), (2, '\u5f85\u53d1\u8d27'), (3, '\u5df2\u53d1\u8d27'), (4, '\u5df2\u5b8c\u6210'), (5, '\u5df2\u5173\u95ed'), (5, '\u9000\u6b3e\u4e2d')], verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
    ]
