# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-07 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0054_order_received_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='received_package',
            new_name='received_packet',
        ),
    ]
