# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-11 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0055_auto_20180407_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '\u5f85\u4ed8\u6b3e'), (1, '\u5df2\u652f\u4ed8'), (2, '\u5f85\u53d1\u8d27'), (3, '\u5df2\u53d1\u8d27'), (4, '\u5df2\u5b8c\u6210'), (5, '\u5df2\u5173\u95ed'), (6, '\u9000\u6b3e\u4e2d')], verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
    ]
