# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-13 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0056_auto_20180411_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.City', verbose_name='\u6240\u5728\u57ce\u5e02'),
        ),
        migrations.AddField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='\u51fa\u751f\u5e74\u6708'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, '\u7537'), (1, '\u5973')], null=True, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u6700\u540e\u767b\u5f55\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='reg_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u8ba2\u5355\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='remindorders',
            name='remind_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u63d0\u9192\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='returngoods',
            name='apply_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='withdraworders',
            name='withdraw_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u63d0\u73b0\u65f6\u95f4'),
        ),
    ]
