# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-04 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0057_auto_20180413_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='balance',
        ),
        migrations.AddField(
            model_name='customer',
            name='clerk',
            field=models.BooleanField(default=False, verbose_name='\u804c\u5458'),
        ),
        migrations.AddField(
            model_name='order',
            name='remind_pay',
            field=models.BooleanField(default=False, verbose_name='\u63d0\u9192\u652f\u4ed8'),
        ),
        migrations.AddField(
            model_name='wxoauth',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='REFRESH_TOKEN'),
        ),
        migrations.AddField(
            model_name='wxoauth',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='REFRESH_TOKEN'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='coupon',
            field=models.ManyToManyField(blank=True, default='', to='goods.Coupon', verbose_name='\u5df2\u9886\u53d6\u4f18\u60e0\u5238'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='enable_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u4f59\u989d'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='follow',
            field=models.ManyToManyField(blank=True, to='goods.GoodsList', verbose_name='\u5173\u6ce8\u5546\u54c1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, '\u7537'), (2, '\u5973')], null=True, verbose_name='\u6027\u522b'),
        ),
    ]
