# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-27 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0059_auto_20180327_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraworders',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='withdraworders',
            name='customer',
        ),
        migrations.DeleteModel(
            name='WithdrawOrders',
        ),
    ]
