# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-27 18:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0060_auto_20180327_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(default='', max_length=16, null=True, verbose_name='\u8ba2\u5355\u7f16\u53f7')),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u63d0\u73b0\u91d1\u989d')),
                ('account', models.CharField(max_length=20, null=True, verbose_name='\u94f6\u884c\u8d26\u53f7')),
                ('status', models.IntegerField(choices=[(0, '\u672a\u5904\u7406'), (1, '\u5df2\u5904\u7406')], default=0, verbose_name='\u72b6\u6001')),
                ('withdraw_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u63d0\u73b0\u65f6\u95f4')),
                ('handing_time', models.DateTimeField(null=True, verbose_name='\u63d0\u73b0\u65f6\u95f4')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.BankBin', verbose_name='\u6240\u5c5e\u94f6\u884c')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='\u6240\u5c5e\u5ba2\u6237')),
            ],
            options={
                'verbose_name': '\u63d0\u73b0\u8ba2\u5355',
                'verbose_name_plural': '\u63d0\u73b0\u8ba2\u5355\u5217\u8868',
            },
        ),
    ]
