# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-17 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0065_auto_20180417_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxoauth',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='REFRESH_TOKEN'),
        ),
        migrations.AddField(
            model_name='wxoauth',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='REFRESH_TOKEN'),
        ),
    ]
