# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-03 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0066_auto_20180417_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='clerk',
            field=models.BooleanField(default=False, verbose_name='\u804c\u5458'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='coupon',
            field=models.ManyToManyField(blank=True, default='', to='goods.Coupon', verbose_name='\u5df2\u9886\u53d6\u4f18\u60e0\u5238'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='follow',
            field=models.ManyToManyField(blank=True, to='goods.GoodsList', verbose_name='\u5173\u6ce8\u5546\u54c1'),
        ),
    ]
