# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodslist',
            name='brands',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.Brand', verbose_name='\u54c1\u724c'),
        ),
    ]
