# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20170809_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brands',
            new_name='name',
        ),
    ]
