# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 14:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20170809_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u4f18\u60e0\u5238\u540d\u79f0')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='\u6298\u6263')),
                ('full', models.IntegerField(verbose_name='\u6ee1')),
                ('dis', models.IntegerField(verbose_name='\u51cf')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('goods', models.ManyToManyField(to='goods.GoodsList', verbose_name='\u5546\u54c1')),
            ],
            options={
                'verbose_name': '\u4f18\u60e0\u5238',
                'verbose_name_plural': '\u4f18\u60e0\u5238\u5217\u8868',
            },
        ),
        migrations.AlterModelOptions(
            name='extraimages',
            options={'verbose_name': '\u989d\u5916\u56fe\u7247', 'verbose_name_plural': '\u989d\u5916\u56fe\u7247\u5217\u8868'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': '\u56fe\u7247', 'verbose_name_plural': '\u56fe\u7247\u5217\u8868'},
        ),
    ]
