# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20170810_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodslist',
            name='classify_one',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.ClassifyOne', verbose_name='\u4e00\u7ea7\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='goodslist',
            name='classify_two',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.ClassifyTwo', verbose_name='\u4e8c\u7ea7\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='goods',
            field=models.ManyToManyField(blank=True, to='goods.GoodsList', verbose_name='\u5546\u54c1'),
        ),
    ]
