# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20170830_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodslist',
            name='classify_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.ClassifyOne', verbose_name='\u4e00\u7ea7\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='goodslist',
            name='classify_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.ClassifyTwo', verbose_name='\u4e8c\u7ea7\u5206\u7c7b'),
        ),
    ]
