# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20170830_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodslist',
            name='classify_one',
        ),
    ]
