# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-31 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_images_classify_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.ClassifyOne', verbose_name='\u4e00\u7ea7\u5206\u7c7b')),
                ('classify_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.ClassifyTwo', verbose_name='\u4e8c\u7ea7\u5206\u7c7b')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.RemoveField(
            model_name='goodslist',
            name='classify_one',
        ),
        migrations.RemoveField(
            model_name='images',
            name='classify_two',
        ),
        migrations.AddField(
            model_name='classify',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsList', verbose_name='\u5546\u54c1'),
        ),
    ]
