# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_auto_20170901_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='explain',
            field=models.TextField(blank=True, verbose_name='\u4f18\u60e0\u8bf4\u660e'),
        ),
    ]
