# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_coupon_explain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='src',
        ),
    ]
