# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_auto_20170901_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Express',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u516c\u53f8\u540d\u79f0')),
                ('code', models.CharField(max_length=10, verbose_name='\u7f16\u7801')),
            ],
            options={
                'verbose_name': '\u5feb\u9012\u516c\u53f8',
                'verbose_name_plural': '\u5feb\u9012\u516c\u53f8\u5217\u8868',
            },
        ),
    ]
