# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-30 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0019_coupon_easy_get'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodslist',
            name='is_dis',
            field=models.BooleanField(default=False, verbose_name='\u9650\u65f6\u6298\u6263'),
        ),
    ]
