# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-09 10:12
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0020_goodslist_is_dis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='goods',
        ),
        migrations.AddField(
            model_name='goodslist',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='goods.Images', verbose_name='\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='goodslist',
            name='detail',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='\u5546\u54c1\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='goodslist',
            name='en_intr',
            field=models.TextField(blank=True, null=True, verbose_name='Goods Intr'),
        ),
        migrations.AlterField(
            model_name='goodslist',
            name='endetail',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='\u5546\u54c1\u8be6\u60c5\uff08\u82f1\u6587\uff09'),
        ),
        migrations.AlterField(
            model_name='goodslist',
            name='intr',
            field=models.TextField(blank=True, null=True, verbose_name='\u5546\u54c1\u7b80\u4ecb'),
        ),
    ]
