# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-09 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0021_auto_20171009_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodslist',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='goods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsList', verbose_name='\u5546\u54c1'),
        ),
    ]
