# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0023_auto_20171010_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodslist',
            name='material_quality',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6750\u8d28'),
        ),
    ]
