# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0024_goodslist_material_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodslist',
            name='dis_price',
        ),
        migrations.RemoveField(
            model_name='goodslist',
            name='integral',
        ),
        migrations.AddField(
            model_name='goodslist',
            name='have_commission',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u4f63\u91d1'),
        ),
    ]
