# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-04 09:57
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0025_auto_20180315_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodslist',
            name='detail',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='\u5546\u54c1\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='goodslist',
            name='endetail',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='\u5546\u54c1\u8be6\u60c5\uff08\u82f1\u6587\uff09'),
        ),
    ]
