# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-04 13:44
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0025_auto_20180315_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifyone',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='goods/classify/', verbose_name='\u4e00\u7ea7\u5206\u7c7b\u56fe\u7247'),
        ),
        migrations.AddField(
            model_name='classifytwo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='goods/classify/', verbose_name='\u4e8c\u7ea7\u5206\u7c7b\u56fe\u7247'),
        ),
        migrations.AddField(
            model_name='classifytwo',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='\u6392\u5e8f'),
        ),
        migrations.AlterField(
            model_name='goodslist',
            name='detail',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='\u5546\u54c1\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='goodslist',
            name='endetail',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='\u5546\u54c1\u8be6\u60c5\uff08\u82f1\u6587\uff09'),
        ),
    ]
