# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-04 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0026_auto_20180404_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifyone',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='goods/classify/', verbose_name='\u4e00\u7ea7\u5206\u7c7b\u56fe\u7247'),
        ),
        migrations.AddField(
            model_name='classifytwo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='goods/classify/', verbose_name='\u4e8c\u7ea7\u5206\u7c7b\u56fe\u7247'),
        ),
        migrations.AddField(
            model_name='classifytwo',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='\u6392\u5e8f'),
        ),
    ]
