# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-10 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0027_auto_20180406_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='stocks_ht',
            field=models.IntegerField(default=0, max_length=100, verbose_name='\u6d3b\u6001\u9986\u5e93\u5b58\u91cf'),
        ),
        migrations.AlterField(
            model_name='images',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsList', verbose_name='\u5546\u54c1'),
        ),
        migrations.AlterField(
            model_name='images',
            name='stocks',
            field=models.IntegerField(default=0, max_length=100, verbose_name='\u4ed3\u5e93\u5e93\u5b58\u91cf'),
        ),
    ]
