# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-12 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0028_auto_20180410_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': '\u5e93\u5b58', 'verbose_name_plural': '\u5e93\u5b58\u5217\u8868'},
        ),
    ]
