# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-12 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0029_auto_20180413_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodslist',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='goodslist',
            name='to_front_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u4e0a\u67b6\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='Visit_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u6d4f\u89c8\u65f6\u95f4'),
        ),
    ]
