# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-04 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0030_auto_20180413_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='stocks',
            field=models.IntegerField(default=0, verbose_name='\u4ed3\u5e93\u5e93\u5b58\u91cf'),
        ),
        migrations.AlterField(
            model_name='images',
            name='stocks_ht',
            field=models.IntegerField(default=0, verbose_name='\u6d3b\u6001\u9986\u5e93\u5b58\u91cf'),
        ),
    ]
