# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170713_1028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='EmailVerifyRecord',
        ),
    ]
