# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '\u7ba1\u7406\u5458', 'verbose_name_plural': '\u7ba1\u7406\u5458\u5217\u8868'},
        ),
    ]
