# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wx', '0002_delete_wxconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u516c\u4f17\u53f7\u540d\u79f0')),
                ('token', models.CharField(max_length=20, verbose_name='Token')),
                ('appid', models.CharField(max_length=40, verbose_name='\u5e94\u7528ID')),
                ('appsecret', models.CharField(max_length=40, verbose_name='\u5e94\u7528secret')),
                ('encrypt_mode', models.CharField(choices=[('normal', '\u660e\u6587'), ('compatible', '\u517c\u5bb9'), ('safe', '\u5b89\u5168')], max_length=15)),
                ('encoding_aes_key', models.CharField(max_length=80, verbose_name='\u6d88\u606f\u52a0\u5bc6\u5bc6\u94a5')),
                ('access_token', models.CharField(max_length=100, verbose_name='ACCESS_TOKEN')),
                ('access_token_expires_at', models.CharField(max_length=20, verbose_name='ACCESS_TOKEN\u6709\u6548\u7ed3\u675f\u65f6\u95f4')),
            ],
        ),
    ]
