# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0003_wxconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('keyword', models.CharField(help_text='\u7528\u6237\u53d1\u51fa\u7684\u5173\u952e\u8bcd', max_length=100, primary_key=True, serialize=False, verbose_name='\u5173\u952e\u8bcd')),
                ('content', models.TextField(blank=True, help_text='\u56de\u590d\u7ed9\u7528\u6237\u7684\u5185\u5bb9', null=True, verbose_name='\u5185\u5bb9')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('published', models.BooleanField(default=True, verbose_name='\u53d1\u5e03\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u5173\u952e\u8bcd',
                'verbose_name_plural': '\u5fae\u4fe1\u56de\u590d\u5173\u952e\u8bcd\u5217\u8868',
            },
        ),
        migrations.AlterModelOptions(
            name='wxconfig',
            options={'verbose_name': '\u5fae\u4fe1\u914d\u7f6e', 'verbose_name_plural': '\u5fae\u4fe1\u914d\u7f6e'},
        ),
    ]
