# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('index', models.IntegerField(verbose_name='\u6392\u5e8f')),
                ('img', models.ImageField(upload_to='banner/image/com/', verbose_name='\u7535\u8111\u5927\u56fe')),
                ('mobile_img', models.ImageField(upload_to='banner/image/mobile/', verbose_name='\u624b\u673a\u5c0f\u56fe')),
                ('url', models.URLField(verbose_name='\u8bbf\u95ee\u5730\u5740')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8f6e\u64ad\u56fe',
                'verbose_name_plural': '\u8f6e\u64ad\u56fe\u5217\u8868',
            },
        ),
    ]
