# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 15:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u4ee3\u8a00\u4eba\u89c4\u5219\u540d')),
                ('first_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='\u4e00\u7ea7\u63a8\u5e7f\u4f63\u91d1\u6bd4')),
                ('second_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='\u4e8c\u7ea7\u63a8\u5e7f\u4f63\u91d1\u6bd4')),
                ('third_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='\u4e09\u7ea7\u63a8\u5e7f\u4f63\u91d1\u6bd4')),
                ('discount', models.IntegerField(verbose_name='\u6298\u6263')),
                ('total_amount', models.IntegerField(default=0, verbose_name='\u7d2f\u8ba1\u63a8\u5e7f\u52a0\u6d88\u8d39\u91d1\u989d')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u751f\u6210\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4ee3\u8a00\u4eba\u89c4\u5219',
                'verbose_name_plural': '\u4ee3\u8a00\u4eba\u89c4\u5219\u5217\u8868',
            },
        ),
    ]
