# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 14:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u4ee3\u8a00\u4eba\u89c4\u5219\u540d')),
                ('first_commission', models.IntegerField(verbose_name='\u4e00\u7ea7\u4f63\u91d1\u6bd4\u4f8b')),
                ('second_commission', models.IntegerField(verbose_name='\u4e8c\u7ea7\u4f63\u91d1\u6bd4\u4f8b')),
                ('third_commission', models.IntegerField(verbose_name='\u4e09\u7ea7\u4f63\u91d1\u6bd4\u4f8b')),
                ('first_discount', models.IntegerField(verbose_name='\u4e00\u7ea7\u6298\u6263')),
                ('second_discount', models.IntegerField(verbose_name='\u4e8c\u7ea7\u6298\u6263')),
                ('third_discount', models.IntegerField(verbose_name='\u4e09\u7ea7\u6298\u6263')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u751f\u6210\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4ee3\u8a00\u4eba\u89c4\u5219',
                'verbose_name_plural': '\u4ee3\u8a00\u4eba\u89c4\u5219\u5217\u8868',
            },
        ),
    ]
