# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_endorsement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endorsement',
        ),
    ]
