# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-04 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_normalquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalquestion',
            name='modify_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
    ]
