# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-07 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20180404_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u7ea2\u5305\u91d1\u989d')),
                ('rate', models.IntegerField(verbose_name='\u9891\u7387')),
                ('min_paid', models.IntegerField(default=0, verbose_name='\u6700\u5c11\u652f\u4ed8\u91d1\u989d')),
                ('enable', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528')),
            ],
            options={
                'verbose_name': '\u7ea2\u5305',
                'verbose_name_plural': '\u7ea2\u5305\u5217\u8868',
            },
        ),
    ]
