# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_endorsement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsement',
            name='first_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='\u4e00\u7ea7\u63a8\u5e7f\u4f63\u91d1\u6bd4'),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='second_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='\u4e8c\u7ea7\u63a8\u5e7f\u4f63\u91d1\u6bd4'),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='third_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='\u4e09\u7ea7\u63a8\u5e7f\u4f63\u91d1\u6bd4'),
        ),
    ]
