# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-12 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_redpacket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='normalquestion',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='verify',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u751f\u6210\u65f6\u95f4'),
        ),
    ]
