# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20180315_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsement',
            name='total_amount',
            field=models.IntegerField(default=0, verbose_name='\u7d2f\u8ba1\u63a8\u5e7f\u91d1'),
        ),
    ]
