# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_endorsement_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsement',
            name='total_amount',
            field=models.IntegerField(default=0, verbose_name='\u7d2f\u8ba1\u63a8\u5e7f\u52a0\u6d88\u8d39\u91d1\u989d'),
        ),
    ]
