# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-04 09:57
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20180315_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u95ee\u9898\u6807\u9898')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='\u95ee\u9898\u5185\u5bb9')),
                ('sort', models.IntegerField(default=0, verbose_name='\u6392\u5e8f')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u751f\u6210\u65f6\u95f4')),
                ('modify_time', models.DateTimeField(blank=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5e38\u89c1\u95ee\u9898',
                'verbose_name_plural': '\u5e38\u89c1\u95ee\u9898\u5217\u8868',
            },
        ),
    ]
