# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-07 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_redpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='redpackage',
            name='min_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='\u6700\u5c11\u652f\u4ed8\u91d1\u989d'),
        ),
    ]
