# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-07 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_redpackage_min_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='redpackage',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u7528'),
        ),
    ]
