# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-07 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20180407_2123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RedPackage',
            new_name='RedPacket',
        ),
    ]
